name: Continuous Integration

# This workflow runs on every pull request that targets the main branch
on:
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo build
        run: cargo build --verbose

      - name: Run cargo test
        run: cargo test --verbose
